//! Local persistence for reviewed games.
//!
//! Until this existed nothing was saved at all: every review — minutes of
//! engine time, and real battery on a phone — was discarded when the app
//! closed, and re-opening the same game re-ran Stockfish from scratch.
//!
//! Two deliberate choices shape what gets written:
//!
//! 1. **Only the engine output is stored, not the classifications.** The
//!    `AnalysisResult` list is the expensive part (minutes of search);
//!    turning it into classifications and explanations was measured at
//!    ~0.37ms per move, so a whole game re-classifies in ~30ms on load.
//!    Storing the cheap half would only create a second copy to keep in
//!    sync — and this way improvements to the classifier or to the
//!    explanation text apply retroactively to games reviewed months ago.
//!
//! 2. **A small summary per game lives in a separate index.** The recent-
//!    games list, and the cross-game weakness stats this unblocks, must
//!    not have to read (or deserialize) every stored game to count how
//!    often someone hangs a piece.
//!
//! The frontend computes summaries, since it already owns the classifier;
//! this module deliberately stays a dumb, typed store rather than growing
//! a second implementation of the review logic in Rust.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};
use tauri::Manager;

use crate::AnalysisResult;

/// Keeps a phone's storage from growing without bound. Oldest reviews are
/// pruned first; at roughly a few KB of engine output per game this is on
/// the order of a handful of megabytes.
const MAX_STORED_REVIEWS: usize = 500;

#[derive(Serialize, Deserialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ReviewSummary {
    pub id: String,
    pub saved_at: i64,
    pub white: String,
    pub black: String,
    pub result: String,
    pub date: String,
    pub move_count: usize,
    pub white_accuracy: f64,
    pub black_accuracy: f64,
    /// Per-colour tallies, keyed by classification name and by motif.
    /// Kept in the summary precisely so cross-game weakness reporting is
    /// a scan of this index rather than a load of every stored game.
    #[serde(default)]
    pub white_counts: HashMap<String, u32>,
    #[serde(default)]
    pub black_counts: HashMap<String, u32>,
    #[serde(default)]
    pub white_motifs: HashMap<String, u32>,
    #[serde(default)]
    pub black_motifs: HashMap<String, u32>,
    /// Opening identity and where the game left known theory. Optional
    /// so summaries written before this existed still deserialize.
    #[serde(default)]
    pub opening: Option<String>,
    #[serde(default)]
    pub eco: Option<String>,
    #[serde(default)]
    pub book_exit_ply: Option<usize>,
    /// How the game ended — a different axis from how it was played.
    #[serde(default)]
    pub termination: Option<String>,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct StoredReview {
    pub summary: ReviewSummary,
    pub pgn: String,
    /// Indexed like the FEN list the review was run over: position 0 is
    /// the starting position, then one entry per ply.
    pub analysis: Vec<AnalysisResult>,
    pub depth: u32,
    pub multi_pv: u32,
}

/// Serializes index read-modify-write cycles. Saving is a read, mutate,
/// and rewrite of the whole index; two reviews finishing close together
/// (easy, since a review can be superseded and restarted) would otherwise
/// race and lose one of the entries.
#[derive(Default)]
pub struct StorageLock(Mutex<()>);

fn reviews_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("Couldn't locate the app data directory: {e}"))?
        .join("reviews");
    fs::create_dir_all(&dir)
        .map_err(|e| format!("Couldn't create {}: {e}", dir.display()))?;
    Ok(dir)
}

fn index_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(reviews_dir(app)?.join("index.json"))
}

/// Ids are content hashes generated by the frontend, but `game_path` is
/// the boundary where one becomes a filesystem path, so it is validated
/// rather than trusted — a value containing `..` or a path separator
/// would otherwise read or write outside the reviews directory.
fn is_valid_review_id(id: &str) -> bool {
    !id.is_empty() && id.chars().all(|c| c.is_ascii_alphanumeric() || c == '-')
}

fn game_path(app: &tauri::AppHandle, id: &str) -> Result<PathBuf, String> {
    if !is_valid_review_id(id) {
        return Err(format!("Refusing to use {id:?} as a review id"));
    }
    Ok(reviews_dir(app)?.join(format!("{id}.json")))
}

/// Writes via a temporary file and a rename, so an interrupted write
/// can't leave a half-written index behind — losing every past review
/// because the app was closed mid-save would be a poor trade.
fn write_atomic(path: &Path, contents: &str) -> Result<(), String> {
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, contents).map_err(|e| format!("Couldn't write {}: {e}", tmp.display()))?;
    fs::rename(&tmp, path).map_err(|e| format!("Couldn't finalize {}: {e}", path.display()))?;
    Ok(())
}

fn read_index(app: &tauri::AppHandle) -> Vec<ReviewSummary> {
    // A missing or corrupt index is recovered from rather than surfaced:
    // saved games are a convenience, and refusing to start because one
    // JSON file went bad would be worse than beginning a fresh index.
    let Ok(path) = index_path(app) else {
        return Vec::new();
    };
    let Ok(raw) = fs::read_to_string(path) else {
        return Vec::new();
    };
    serde_json::from_str(&raw).unwrap_or_default()
}

#[tauri::command]
pub fn list_reviews(app: tauri::AppHandle) -> Vec<ReviewSummary> {
    let mut index = read_index(&app);
    index.sort_by(|a, b| b.saved_at.cmp(&a.saved_at));
    index
}

#[tauri::command]
pub fn load_review(app: tauri::AppHandle, id: String) -> Result<StoredReview, String> {
    let path = game_path(&app, &id)?;
    let raw = fs::read_to_string(&path)
        .map_err(|_| "That saved review is no longer available.".to_string())?;
    serde_json::from_str(&raw).map_err(|e| format!("That saved review couldn't be read: {e}"))
}

#[tauri::command]
pub fn save_review(
    app: tauri::AppHandle,
    lock: tauri::State<StorageLock>,
    review: StoredReview,
) -> Result<(), String> {
    let _guard = lock.0.lock().map_err(|_| "Storage lock poisoned".to_string())?;

    let path = game_path(&app, &review.summary.id)?;
    let body = serde_json::to_string(&review).map_err(|e| e.to_string())?;
    write_atomic(&path, &body)?;

    let mut index = read_index(&app);
    // Re-reviewing a game replaces its entry rather than adding a second:
    // ids are content hashes of the PGN, so the same game imported twice
    // is the same id.
    index.retain(|s| s.id != review.summary.id);
    index.push(review.summary);
    index.sort_by(|a, b| b.saved_at.cmp(&a.saved_at));

    if index.len() > MAX_STORED_REVIEWS {
        for pruned in index.split_off(MAX_STORED_REVIEWS) {
            if let Ok(p) = game_path(&app, &pruned.id) {
                let _ = fs::remove_file(p);
            }
        }
    }

    let index_body = serde_json::to_string(&index).map_err(|e| e.to_string())?;
    write_atomic(&index_path(&app)?, &index_body)
}

#[tauri::command]
pub fn delete_review(
    app: tauri::AppHandle,
    lock: tauri::State<StorageLock>,
    id: String,
) -> Result<(), String> {
    let _guard = lock.0.lock().map_err(|_| "Storage lock poisoned".to_string())?;

    let path = game_path(&app, &id)?;
    let _ = fs::remove_file(path);

    let mut index = read_index(&app);
    index.retain(|s| s.id != id);
    let index_body = serde_json::to_string(&index).map_err(|e| e.to_string())?;
    write_atomic(&index_path(&app)?, &index_body)
}

#[cfg(test)]
mod tests {
    use super::*;

    // `game_path` itself needs an AppHandle, so these exercise the
    // validation predicate it delegates to — the property that matters is
    // that no id reaching the filesystem can contain a separator or
    // traversal segment.
    #[test]
    fn rejects_ids_that_could_escape_the_reviews_directory() {
        for id in [
            "../secret",
            "a/b",
            "..",
            "",
            "with space",
            "semi;colon",
            "back\\slash",
            "null\0byte",
            "dot.dot",
        ] {
            assert!(
                !is_valid_review_id(id),
                "{id:?} should be rejected as a review id"
            );
        }
    }

    #[test]
    fn accepts_content_hash_ids() {
        for id in ["a1b2c3d4", "0", "abc-123", "deadbeefcafe0123"] {
            assert!(
                is_valid_review_id(id),
                "{id:?} should be accepted as a review id"
            );
        }
    }
}
